### ISSUE TITLE
Parameter -o for output file is not working

### ISSUE THREAD

**Issue by edulemasson** [WHOIGit/DrawBox#1]
I run the command in the readme file: python3 DrawBox.py -o output.json data/images/*.jpg

and what I got is:

usage: drawBox.py [-h] [--read-only] files [files ...]
drawBox.py: error: unrecognized arguments: -o

**Comment by rgov** [comment]
Hi, thanks for trying this out. The README is outdated, as you found. How it works now is you simply invoke:

```
python3 DrawBox.py a.jpg b.jpg c.jpg
```

and it will output files `a.txt`, `b.txt`, `c.txt` which are in the annotation format used by Darknet (YOLO). If one of the `.txt` files already exists, it will be loaded and you'll see the existing annotations and can modify them.

The only option is `--read-only` which prevents modifying any existing `.txt` files.
